import { useState } from "react";
import {
  UploadCloud,
  FileText,
  Loader2,
  ShieldCheck,
  AlertTriangle,
  ClipboardList,
  Sparkles,
  CheckCircle2,
} from "lucide-react";
import { toast } from "react-toastify";
import api from "../services/api";
import { useLanguage } from "../context/LanguageContext";

function ReportAnalyzer() {
  const [file, setFile] = useState(null);
  const [result, setResult] = useState("");
  const [loading, setLoading] = useState(false);

  const { language } = useLanguage();

  const content = {
    en: {
      header: "AI Medical Report Analyzer",
      description:
        "Upload your medical report and receive an easy-to-understand AI explanation.",
      uploadTitle: "Upload Your Medical Report",
      uploadDescription:
        "Drag and drop your PDF here or click to browse your files.",
      uploadHint: "Supported format: PDF",
      selectedFile: "Selected File",
      analyze: "Analyze Report",
      analyzing: "AI is analyzing your report...",
      progressTitle: "AI Analysis in Progress",
      progressDescription:
        "Please wait while MediMind AI reviews your report.",
      analysis: "AI Analysis",
      recommendation: "Professional Recommendation",
      recommendationText:
        "Review this AI-generated explanation carefully and consult a qualified healthcare professional before making any medical decisions.",
      disclaimer: "Medical Disclaimer",
      disclaimerText:
        "This analysis is generated by AI for educational purposes only. It is not a substitute for professional medical advice, diagnosis, or treatment.",
      uploadWarning: "Please upload a PDF report.",
      success: "Report analyzed successfully!",
      failed: "Failed to analyze report.",
      secure: "Secure Analysis",
      simple: "Simple Explanation",
      smart: "AI-Powered",
    },

    te: {
      header: "AI వైద్య రిపోర్ట్ విశ్లేషణ",
      description:
        "మీ వైద్య రిపోర్ట్‌ను అప్‌లోడ్ చేసి సులభంగా అర్థం చేసుకునే AI వివరణను పొందండి.",
      uploadTitle: "మీ వైద్య రిపోర్ట్‌ను అప్‌లోడ్ చేయండి",
      uploadDescription:
        "మీ PDF ను ఇక్కడ డ్రాగ్ చేసి వదలండి లేదా ఫైల్ ఎంచుకోవడానికి క్లిక్ చేయండి.",
      uploadHint: "మద్దతు ఉన్న ఫార్మాట్: PDF",
      selectedFile: "ఎంచుకున్న ఫైల్",
      analyze: "రిపోర్ట్‌ను విశ్లేషించండి",
      analyzing: "AI మీ రిపోర్ట్‌ను విశ్లేషిస్తోంది...",
      progressTitle: "AI విశ్లేషణ జరుగుతోంది",
      progressDescription:
        "MediMind AI మీ రిపోర్ట్‌ను పరిశీలిస్తున్నప్పుడు దయచేసి వేచి ఉండండి.",
      analysis: "AI విశ్లేషణ",
      recommendation: "వైద్య నిపుణుల సూచన",
      recommendationText:
        "ఈ AI రూపొందించిన వివరణను జాగ్రత్తగా పరిశీలించండి. ఏదైనా వైద్య నిర్ణయం తీసుకునే ముందు అర్హత కలిగిన వైద్య నిపుణుడిని సంప్రదించండి.",
      disclaimer: "వైద్య నిరాకరణ ప్రకటన",
      disclaimerText:
        "ఈ విశ్లేషణ AI ద్వారా విద్యాపరమైన ప్రయోజనాల కోసం మాత్రమే రూపొందించబడింది. ఇది వృత్తిపరమైన వైద్య సలహా, నిర్ధారణ లేదా చికిత్సకు ప్రత్యామ్నాయం కాదు.",
      uploadWarning: "దయచేసి PDF రిపోర్ట్‌ను అప్‌లోడ్ చేయండి.",
      success: "రిపోర్ట్ విజయవంతంగా విశ్లేషించబడింది!",
      failed: "రిపోర్ట్‌ను విశ్లేషించడం విఫలమైంది.",
      secure: "సురక్షితమైన విశ్లేషణ",
      simple: "సులభమైన వివరణ",
      smart: "AI ఆధారిత సేవ",
    },
  };

  const text = content[language];

  const analyzeReport = async () => {
    if (!file) {
      toast.warning(text.uploadWarning);
      return;
    }

    const formData = new FormData();

    formData.append("file", file);

    formData.append(
      "language",
      language === "te" ? "Telugu" : "English"
    );

    try {
      setLoading(true);

      const response = await api.post(
        "/analyze-report",
        formData,
        {
          headers: {
            "Content-Type": "multipart/form-data",
          },
        }
      );

      setResult(response.data.analysis);

      toast.success(text.success);
    } catch (error) {
      console.error(error);
      toast.error(text.failed);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="bg-white rounded-3xl overflow-hidden">

      {/* =====================================================
          COMPONENT HEADER
      ===================================================== */}

      <div className="relative overflow-hidden rounded-2xl bg-gradient-to-br from-[#E5F2F3] via-white to-[#F6EFD2] border border-[#DCE8E5] p-6 sm:p-7">

        <div className="absolute -right-12 -top-16 w-40 h-40 rounded-full bg-[#D9ECEE]/50" />

        <div className="relative z-10 flex items-center gap-4">

          <div className="w-14 h-14 shrink-0 rounded-2xl bg-[#0E6F78] text-white flex items-center justify-center shadow-md">
            <ClipboardList size={30} />
          </div>

          <div>

            <div className="flex items-center gap-2 mb-1">

              <h2 className="text-xl sm:text-2xl font-extrabold text-[#083E44]">
                {text.header}
              </h2>

              <Sparkles
                size={18}
                className="text-[#C9A227]"
              />

            </div>

            <p className="text-sm leading-6 text-[#625C56]">
              {text.description}
            </p>

          </div>

        </div>

      </div>

      {/* =====================================================
          FEATURE BADGES
      ===================================================== */}

      <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 mt-5">

        <div className="flex items-center gap-3 rounded-xl border border-[#D8E7E5] bg-[#F7FBFA] p-3.5">

          <div className="w-9 h-9 rounded-lg bg-[#E5F2F3] text-[#0E6F78] flex items-center justify-center">
            <ShieldCheck size={19} />
          </div>

          <span className="text-xs font-bold text-[#3F514F]">
            {text.secure}
          </span>

        </div>

        <div className="flex items-center gap-3 rounded-xl border border-[#E8DCA9] bg-[#FFFDF5] p-3.5">

          <div className="w-9 h-9 rounded-lg bg-[#F6EFD2] text-[#A18416] flex items-center justify-center">
            <FileText size={19} />
          </div>

          <span className="text-xs font-bold text-[#5D5538]">
            {text.simple}
          </span>

        </div>

        <div className="flex items-center gap-3 rounded-xl border border-[#D8E7E5] bg-[#F7FBFA] p-3.5">

          <div className="w-9 h-9 rounded-lg bg-[#E5F2F3] text-[#0E6F78] flex items-center justify-center">
            <Sparkles size={18} />
          </div>

          <span className="text-xs font-bold text-[#3F514F]">
            {text.smart}
          </span>

        </div>

      </div>

      {/* =====================================================
          UPLOAD AREA
      ===================================================== */}

      <div className="mt-6">

        <label
          htmlFor="report-upload"
          className="
            group
            block
            cursor-pointer
            rounded-2xl
            border-2
            border-dashed
            border-[#A9CED1]
            bg-gradient-to-br from-[#F8FCFC] to-[#F1F7F6]
            p-8
            sm:p-11
            text-center
            hover:border-[#0E6F78]
            hover:bg-[#EEF7F7]
            transition-all
            duration-300
          "
        >

          <div className="mx-auto mb-5 w-16 h-16 rounded-2xl bg-[#D9ECEE] text-[#0E6F78] flex items-center justify-center group-hover:scale-105 transition-transform duration-300">

            <UploadCloud size={34} />

          </div>

          <h3 className="text-xl sm:text-2xl font-extrabold text-[#1C1A16] mb-2">
            {text.uploadTitle}
          </h3>

          <p className="text-sm text-[#6B655E]">
            {text.uploadDescription}
          </p>

          <div className="mt-4 inline-flex items-center gap-2 rounded-full bg-white border border-[#DDE8E6] px-4 py-2">

            <FileText
              size={15}
              className="text-[#0E6F78]"
            />

            <span className="text-xs font-semibold text-[#6B655E]">
              {text.uploadHint}
            </span>

          </div>

          <input
            id="report-upload"
            type="file"
            accept=".pdf"
            className="hidden"
            onChange={(e) => {
              const selectedFile = e.target.files?.[0];

              if (selectedFile) {
                setFile(selectedFile);
                setResult("");
              }
            }}
          />

        </label>

      </div>

      {/* =====================================================
          SELECTED FILE
      ===================================================== */}

      {file && (
        <div className="mt-5 rounded-2xl border border-[#C9E5D3] bg-[#F3FAF5] p-4">

          <div className="flex items-center gap-3">

            <div className="w-11 h-11 shrink-0 rounded-xl bg-[#DDF0E3] text-[#1F7A4C] flex items-center justify-center">

              <FileText size={23} />

            </div>

            <div className="min-w-0 flex-1">

              <div className="flex items-center gap-2">

                <p className="text-xs font-bold text-[#17613C]">
                  {text.selectedFile}
                </p>

                <CheckCircle2
                  size={15}
                  className="text-[#1F7A4C]"
                />

              </div>

              <p className="text-sm font-semibold text-[#3F5147] break-all mt-1">
                {file.name}
              </p>

            </div>

          </div>

        </div>
      )}

      {/* =====================================================
          ANALYZE BUTTON
      ===================================================== */}

      <button
        onClick={analyzeReport}
        disabled={loading}
        className="
          mt-6
          w-full
          bg-[#0E6F78]
          hover:bg-[#083E44]
          disabled:bg-[#A8B5B5]
          text-white
          py-4
          rounded-xl
          font-bold
          flex
          justify-center
          items-center
          gap-3
          transition-all
          duration-200
          shadow-sm
          hover:shadow-lg
        "
      >

        {loading ? (
          <>
            <Loader2
              size={22}
              className="animate-spin"
            />

            {text.analyzing}
          </>
        ) : (
          <>
            <ShieldCheck size={22} />

            {text.analyze}
          </>
        )}

      </button>

      {/* =====================================================
          LOADING
      ===================================================== */}

      {loading && (
        <div className="mt-7 rounded-2xl border border-[#C7E1E3] bg-gradient-to-br from-[#E5F2F3] to-[#F7F5F1] p-8 text-center">

          <div className="mx-auto w-16 h-16 rounded-full bg-white shadow-sm flex items-center justify-center">

            <Loader2
              className="animate-spin text-[#0E6F78]"
              size={35}
            />

          </div>

          <h3 className="font-extrabold text-xl mt-5 text-[#083E44]">
            {text.progressTitle}
          </h3>

          <p className="text-[#625C56] mt-2 text-sm">
            {text.progressDescription}
          </p>

          <div className="mt-5 mx-auto max-w-xs h-1.5 bg-white rounded-full overflow-hidden">

            <div className="h-full w-2/3 bg-[#0E6F78] rounded-full animate-pulse" />

          </div>

        </div>
      )}

      {/* =====================================================
          RESULT
      ===================================================== */}

      {result && !loading && (
        <div className="mt-9 space-y-5">

          {/* AI ANALYSIS */}

          <div className="rounded-2xl border border-[#C7E1E3] bg-[#F2F9F9] overflow-hidden">

            <div className="flex items-center gap-3 px-6 py-5 border-b border-[#D8E9E9]">

              <div className="w-11 h-11 rounded-xl bg-[#0E6F78] text-white flex items-center justify-center">

                <ClipboardList size={23} />

              </div>

              <div>

                <h2 className="text-xl font-extrabold text-[#083E44]">
                  {text.analysis}
                </h2>

                <p className="text-xs text-[#6B7776] mt-0.5">
                  MediMind AI
                </p>

              </div>

            </div>

            <div className="p-6">

              <p className="whitespace-pre-wrap leading-8 text-[#4E5755]">
                {result}
              </p>

            </div>

          </div>

          {/* RECOMMENDATION */}

          <div className="rounded-2xl border border-[#C9E5D3] bg-[#F4FAF6] p-6">

            <div className="flex items-center gap-3 mb-4">

              <div className="w-11 h-11 rounded-xl bg-[#1F7A4C] text-white flex items-center justify-center">

                <ShieldCheck size={23} />

              </div>

              <h2 className="text-xl font-extrabold text-[#17613C]">
                {text.recommendation}
              </h2>

            </div>

            <p className="text-[#555E59] leading-7">
              {text.recommendationText}
            </p>

          </div>

          {/* DISCLAIMER */}

          <div className="rounded-2xl border border-[#F3C5C1] border-l-4 border-l-[#B42318] bg-[#FEF4F3] p-6">

            <div className="flex gap-3">

              <div className="w-11 h-11 shrink-0 rounded-xl bg-[#FDE3E0] text-[#B42318] flex items-center justify-center">

                <AlertTriangle size={23} />

              </div>

              <div>

                <h2 className="font-extrabold text-xl text-[#982018]">
                  {text.disclaimer}
                </h2>

                <p className="text-[#5E5754] mt-2 leading-7">
                  {text.disclaimerText}
                </p>

              </div>

            </div>

          </div>

        </div>
      )}

    </div>
  );
}

export default ReportAnalyzer;